[package]
name = "vaultx-policy"
version.workspace = true
edition.workspace = true

license.workspace = true
publish.workspace = true
[dependencies]
serde = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
vaultx-types = { path = "../vaultx-types" }

[dev-dependencies]
tempfile = { workspace = true }
