[package]
name = "vaultx-keyring"
version.workspace = true
edition.workspace = true

license.workspace = true
publish.workspace = true
[dependencies]
hex = { workspace = true }
rand_core = { workspace = true }
vaultx-crypto = { path = "../vaultx-crypto" }

[dev-dependencies]
tempfile = { workspace = true }
