[package]
name = "vaultx-broker"
version.workspace = true
edition.workspace = true

[dependencies]
base64 = { workspace = true }
getrandom = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
subtle = { workspace = true }
thiserror = { workspace = true }
vaultx-audit = { path = "../vaultx-audit" }
vaultx-crypto = { path = "../vaultx-crypto" }
vaultx-http = { path = "../vaultx-http" }
vaultx-policy = { path = "../vaultx-policy" }
vaultx-types = { path = "../vaultx-types" }

[dev-dependencies]
tempfile = { workspace = true }
