[package]
name = "vaultx-cli"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "vaultx"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
rpassword = { workspace = true }
thiserror = { workspace = true }
vaultx-core = { path = "../vaultx-core" }
vaultx-types = { path = "../vaultx-types" }

[dev-dependencies]
tempfile = { workspace = true }
